name: sacred
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - cpuonly
  - rdkit
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pip
  - pip:
    - transformers>=4.30.0
    - tqdm
    - pyyaml
    - selfies
    - torch-geometric
    - torch-scatter
    - torch-sparse
    - torch-cluster
    - torch-spline-conv